Listen __PORT__

<VirtualHost *:__PORT__>
    DocumentRoot /var/www/FreshRSS/p

    <Directory /var/www/FreshRSS/p>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    # Redirect bare root to the FreshRSS index
    RedirectMatch ^/$ /index.php

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
